# This workflow will do a clean installation of node dependencies, build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build - Release - Publish

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Perform clean install
      run: npm ci

    - name: Upload dist folder
      uses: actions/upload-artifact@v3.1.3
      with:
        name: distArtifact
        path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download dist folder
      uses: actions/download-artifact@v2.1.1
      with:
        name: distArtifact
        path: dist

    - name: Show dist directory contents
      run: |
        cd dist
        ls

    - name: Create tarball
      run: tar -zcvf dist.tar.gz dist

    # - name: Delete previous prerelease
    #   env:
    #     GH_TOKEN: ${{github.token}}
    #   run: gh release delete prerelease --yes

    - name: Make a new release with tarbal
      env:
        GH_TOKEN: ${{github.token}}
      run: gh release create prerelease dist.tar.gz --notes-file changelog.md --prerelease

  publish:
    needs: [build, release]
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@v2.1.1
        with:
          name: distArtifact
          path: dist

      - name: Pack for NPM
        run: npm pack
        
      - name: Release to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ONTARIOLRC_ANGULAR_MATERIAL_STYLES}}
        run: npm publish --tag prerelease --access public
